#!usr/bin/env ruby

# Install needed dependencies
Bundler.with_clean_env do
  system("gem install brakeman")
  system("gem install bundler-audit")

  # Run checks
  brakeman_res = system("brakeman -A")
  bundler_res = system("bundle audit check --update")

  # ignore warnings on PR/branch-triggered runs
  exit 0 if (ENV["TRAVIS_EVENT_TYPE"] != "cron")

  exit (brakeman_res || bundler_res)
end
